
/*
	$boilerplate$ is the path to the prefab we want to use. You need the l4d2_survivor_boilerplate part
	In this example, we are creating a model that will replace the "light" version of Francis,
	the one used in the intro cutscene for The Passing.
*/

$definevariable boilerplate "l4d2_survivor_boilerplate/francis_light.qci"

$modelname "survivors/survivor_biker_light.mdl"

$include "example_base.qci"
